apiVersion: apps/v1
kind: Deployment
metadata:
   name: my-simple-app
spec:
  selector:
    matchLabels:
      app: my-simple-app
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-simple-app
    spec:
      containers:
      - name: my-simple-app
        image: antonk2234/spring_application:latest
        ports:
        - containerPort: 8080
