apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
         - name: mysql
           containerPort: 3306
           protocol: TCP
        volumeMounts:
        - name: k8s-mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: k8s-mysql-storage